import type {
  ChangelogEntry,
  Claim,
  CorrectionRequest,
  Expert,
  LaunchGate,
  Resolution,
  ScoringVersion,
  SiteDataset,
  SourceDocument,
} from "@/lib/types";

const experts: Expert[] = [
  {
    id: "expert-roubini",
    slug: "nouriel-roubini",
    displayName: "Nouriel Roubini",
    headline: "Macro strategist tracking inflation, recession risk, and the Fed.",
    organization: "Roubini Macro Associates",
    avatarUrl: "/avatars/roubini.svg",
    bio: "Bearish macro calls with a high-conviction style that translates well into public scorecards.",
    domain: "macro",
    featured: true,
    socialLinks: {
      x: "https://example.com/roubini",
    },
  },
  {
    id: "expert-cathie",
    slug: "cathie-wood",
    displayName: "Cathie Wood",
    headline: "Growth-first macro commentator leaning into risk, innovation, and easing cycles.",
    organization: "ARK Invest",
    avatarUrl: "/avatars/cathie.svg",
    bio: "Public macro views often skew optimistic, making the compare format especially sharp.",
    domain: "macro",
    featured: true,
    socialLinks: {
      x: "https://example.com/cathie",
    },
  },
  {
    id: "expert-elerian",
    slug: "mohamed-el-erian",
    displayName: "Mohamed El-Erian",
    headline: "Measured macro calls with strong policy framing and timing discipline.",
    organization: "Queens' College, Cambridge",
    avatarUrl: "/avatars/elerian.svg",
    bio: "Consistently specific calls on rates, inflation, and labor without overcommitting to extremes.",
    domain: "macro",
    featured: true,
    socialLinks: {
      x: "https://example.com/elerian",
    },
  },
  {
    id: "expert-lyn",
    slug: "lyn-alden",
    displayName: "Lyn Alden",
    headline: "Cross-asset macro analysis with a steady bias toward explicit thresholds.",
    organization: "Lyn Alden Investment Strategy",
    avatarUrl: "/avatars/lyn.svg",
    bio: "The cleanest sample set in the mock board, with high specificity and low narrative spillover.",
    domain: "macro",
    featured: true,
    socialLinks: {
      x: "https://example.com/lyn",
    },
  },
  {
    id: "expert-yardeni",
    slug: "ed-yardeni",
    displayName: "Ed Yardeni",
    headline: "Wall Street macro commentary with broad market and rates positioning.",
    organization: "Yardeni Research",
    avatarUrl: "/avatars/yardeni.svg",
    bio: "Optimistic market calls paired with middle-of-the-road confidence language.",
    domain: "macro",
    featured: false,
    socialLinks: {
      x: "https://example.com/yardeni",
    },
  },
  {
    id: "expert-cramer",
    slug: "jim-cramer",
    displayName: "Jim Cramer",
    headline: "High-volume market commentary with aggressive directional framing.",
    organization: "CNBC",
    avatarUrl: "/avatars/cramer.svg",
    bio: "A low-score foil in the sample data that makes the ranking spread obvious.",
    domain: "macro",
    featured: false,
    socialLinks: {
      x: "https://example.com/cramer",
    },
  },
];

const scoringVersions: ScoringVersion[] = [
  {
    id: "score-v0-9",
    version: "v0.9",
    label: "Calibration preview",
    status: "superseded",
    priorQuality: 0.61,
    shrinkageK: 16,
    tierMap: {
      low: 0.55,
      medium: 0.7,
      high: 0.85,
    },
    activatedAt: "2026-01-08T09:00:00.000Z",
    calibratedAt: "2026-01-04T09:00:00.000Z",
    baselineResolvedClaims: 182,
    nextReviewAt: "2026-04-08T09:00:00.000Z",
    highlightUntil: "2026-01-22T09:00:00.000Z",
    changelogTitle: "Calibration preview retired",
    changelogSummary: "Earlier candidate config used a heavier shrinkage factor and a wider high-tier spread.",
  },
  {
    id: "score-v1-0",
    version: "v1.0",
    label: "Launch scoring",
    status: "active",
    priorQuality: 0.64,
    shrinkageK: 12,
    tierMap: {
      low: 0.6,
      medium: 0.7,
      high: 0.8,
    },
    activatedAt: "2026-03-03T09:00:00.000Z",
    calibratedAt: "2026-02-24T09:00:00.000Z",
    baselineResolvedClaims: 412,
    nextReviewAt: "2026-06-30T09:00:00.000Z",
    highlightUntil: "2026-03-17T09:00:00.000Z",
    changelogTitle: "Scoring v1.0 applied",
    changelogSummary: "Launch version freezes prior quality, shrinkage K, and the tier map for the entire quarter.",
  },
];

const activeScoreVersion = scoringVersions[1];

const sourceDocuments: SourceDocument[] = [];
const claims: Claim[] = [];
const resolutions: Resolution[] = [];

let sourceCounter = 1;
let claimCounter = 1;
let resolutionCounter = 1;

function addClaim(args: {
  expertSlug: string;
  title: string;
  platform: string;
  url: string;
  publishedAt: string;
  eventKey: string;
  eventLabel: string;
  quote: string;
  claimType: Claim["claimType"];
  predictedOutcome: Claim["predictedOutcome"];
  confidenceTier?: Claim["confidenceTier"];
  explicitProbability?: number;
  deadline: string;
  operator: string;
  metricKey: string;
  metricLabel: string;
  threshold?: number;
  unit: string;
  status: Claim["status"];
  actualValue?: string;
  outcome?: Resolution["outcome"];
  evidenceUrl?: string;
  resolvedAt?: string;
  notes?: string;
  settlementPolicy?: Resolution["settlementPolicy"];
  settledStage?: Resolution["settledStage"];
  officialReleaseDate?: string;
  initialReleaseValue?: string;
  initialReleaseAt?: string;
  revisedValue?: string;
  revisedAt?: string;
  revisionHandling?: Resolution["revisionHandling"];
  revisionNotes?: string;
  rejectionReason?: string;
  llmSuggestedClaimType?: Claim["claimType"];
  llmSuggestedTier?: Claim["confidenceTier"];
  llmConfidence?: number;
  operatorOverride?: boolean;
  overrideReason?: string;
}) {
  const expert = experts.find((item) => item.slug === args.expertSlug);
  if (!expert) {
    throw new Error(`Unknown expert slug: ${args.expertSlug}`);
  }

  const sourceId = `source-${sourceCounter++}`;
  const claimId = `claim-${claimCounter++}`;

  sourceDocuments.push({
    id: sourceId,
    expertId: expert.id,
    title: args.title,
    platform: args.platform,
    url: args.url,
    publishedAt: args.publishedAt,
  });

  claims.push({
    id: claimId,
    expertId: expert.id,
    sourceDocumentId: sourceId,
    eventKey: args.eventKey,
    eventLabel: args.eventLabel,
    quotedText: args.quote,
    publishedAt: args.publishedAt,
    deadline: args.deadline,
    claimType: args.claimType,
    predictedOutcome: args.predictedOutcome,
    status: args.status,
    scoreVersion: activeScoreVersion.version,
    resolutionRule: {
      claimType: args.claimType,
      metricKey: args.metricKey,
      metricLabel: args.metricLabel,
      operator: args.operator,
      threshold: args.threshold,
      unit: args.unit,
      deadline: args.deadline,
    },
    explicitProbability: args.explicitProbability,
    confidenceTier: args.confidenceTier,
    tierAssignmentReason:
      args.confidenceTier === "high"
        ? "Contains clear conviction language such as will, strongly, or no doubt."
        : args.confidenceTier === "medium"
          ? "Uses likely/base-case framing without absolute certainty."
          : args.confidenceTier === "low"
            ? "Uses possible/risk framing without a hard commitment."
            : undefined,
    tierAssignedBy: args.status === "rejected_unscoreable" ? undefined : "ops-nadia",
    tierAssignedAt: args.status === "rejected_unscoreable" ? undefined : "2026-03-04T12:00:00.000Z",
    reviewedBy: "ops-nadia",
    reviewedAt: "2026-03-04T13:15:00.000Z",
    rejectionReason: args.rejectionReason,
    llmSuggestedClaimType: args.llmSuggestedClaimType ?? args.claimType,
    llmSuggestedTier: args.llmSuggestedTier ?? args.confidenceTier,
    llmConfidence: args.llmConfidence ?? 0.82,
    llmModelVersion: "gpt-5.4-mini-2026-03-01",
    operatorOverride: args.operatorOverride ?? false,
    overrideReason: args.overrideReason,
    sourceSpan: args.quote,
  });

  if (args.status === "resolved") {
    resolutions.push({
      id: `resolution-${resolutionCounter++}`,
      claimId,
      outcome: args.outcome ?? "yes",
      actualValue: args.actualValue ?? "",
      evidenceUrl: args.evidenceUrl ?? "https://example.com/evidence",
      resolvedAt: args.resolvedAt ?? args.deadline,
      settlementPolicy: args.settlementPolicy ?? "first_official_release",
      settledStage: args.settledStage ?? "official_preliminary",
      officialReleaseDate: args.officialReleaseDate ?? args.resolvedAt ?? args.deadline,
      initialReleaseValue: args.initialReleaseValue ?? args.actualValue ?? "",
      initialReleaseAt: args.initialReleaseAt ?? args.resolvedAt ?? args.deadline,
      revisedValue: args.revisedValue,
      revisedAt: args.revisedAt,
      revisionHandling: args.revisionHandling ?? (args.revisedValue ? "tracked_no_rescore" : undefined),
      revisionNotes: args.revisionNotes,
      reviewerId: "ops-maya",
      reviewerName: "Maya",
      notes: args.notes ?? "Resolved against official release.",
    });
  }
}

addClaim({
  expertSlug: "nouriel-roubini",
  title: "Fed will pivot by Q3",
  platform: "TV interview",
  url: "https://example.com/roubini-fed-q3",
  publishedAt: "2024-02-12T10:00:00.000Z",
  eventKey: "fed-first-cut-by-q3-2024",
  eventLabel: "Fed delivers its first cut by the end of Q3 2024",
  quote: "The Fed will have to start cutting by Q3 if growth keeps cooling.",
  claimType: "first_action_by_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2024-09-30T23:59:59.000Z",
  operator: "first_action_on_or_before",
  metricKey: "fed_funds_first_cut",
  metricLabel: "First Fed cut date",
  unit: "date",
  status: "resolved",
  outcome: "yes",
  actualValue: "2024-09-18",
  evidenceUrl: "https://example.com/evidence/fed-first-cut",
  resolvedAt: "2024-09-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "nouriel-roubini",
  title: "Three Fed cuts land in 2024",
  platform: "Newsletter",
  url: "https://example.com/roubini-cuts-2024",
  publishedAt: "2024-03-21T09:00:00.000Z",
  eventKey: "fed-three-cuts-2024",
  eventLabel: "Fed delivers at least three cuts in 2024",
  quote: "By year-end I expect at least three cuts as the growth scare deepens.",
  claimType: "count_by_deadline",
  predictedOutcome: "yes",
  confidenceTier: "high",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than_or_equal",
  metricKey: "fed_cuts_count_2024",
  metricLabel: "Fed cuts in 2024",
  threshold: 3,
  unit: "cuts",
  status: "resolved",
  outcome: "yes",
  actualValue: "3",
  evidenceUrl: "https://example.com/evidence/fed-cuts-count",
  resolvedAt: "2024-12-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "nouriel-roubini",
  title: "Recession lands by Q2 2025",
  platform: "Panel transcript",
  url: "https://example.com/roubini-recession",
  publishedAt: "2024-06-05T16:00:00.000Z",
  eventKey: "us-recession-by-q2-2025",
  eventLabel: "US enters recession by Q2 2025",
  quote: "I strongly believe recession is coming by the second quarter of 2025.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "yes",
  confidenceTier: "high",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "equals",
  metricKey: "nber_recession_start",
  metricLabel: "NBER recession start",
  threshold: 1,
  unit: "binary",
  status: "resolved",
  outcome: "no",
  actualValue: "0",
  evidenceUrl: "https://example.com/evidence/nber-q2-2025",
  resolvedAt: "2025-07-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "nouriel-roubini",
  title: "Labor softens hard",
  platform: "Substack",
  url: "https://example.com/roubini-unemployment",
  publishedAt: "2024-07-10T12:00:00.000Z",
  eventKey: "unemployment-above-4-5-end-2024",
  eventLabel: "US unemployment ends 2024 above 4.5%",
  quote: "Expect unemployment north of 4.5% by year end.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "us_unemployment_rate_end_2024",
  metricLabel: "US unemployment rate",
  threshold: 4.5,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "4.1",
  evidenceUrl: "https://example.com/evidence/unemployment-2024",
  resolvedAt: "2025-01-10T13:00:00.000Z",
  officialReleaseDate: "2025-01-10T13:00:00.000Z",
  initialReleaseValue: "4.1",
  initialReleaseAt: "2025-01-10T13:00:00.000Z",
  revisedValue: "4.2",
  revisedAt: "2025-03-07T13:00:00.000Z",
  revisionHandling: "tracked_no_rescore",
  revisionNotes: "AYRE v1.0 settles this claim on the first official BLS release and logs later revisions without retroactive rescoring.",
});
addClaim({
  expertSlug: "nouriel-roubini",
  title: "Inflation stays sticky",
  platform: "TV interview",
  url: "https://example.com/roubini-cpi",
  publishedAt: "2024-08-02T12:00:00.000Z",
  eventKey: "cpi-below-3-end-2024",
  eventLabel: "US CPI ends 2024 below 3.0%",
  quote: "No, inflation will not get below 3% by year end.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "high",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us_cpi_yoy_end_2024",
  metricLabel: "US CPI YoY",
  threshold: 3,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "3.2",
  evidenceUrl: "https://example.com/evidence/cpi-2024",
  resolvedAt: "2025-01-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "nouriel-roubini",
  title: "Equities remain capped",
  platform: "Newsletter",
  url: "https://example.com/roubini-spx",
  publishedAt: "2024-08-22T13:00:00.000Z",
  eventKey: "spx-above-5500-end-2024",
  eventLabel: "S&P 500 ends 2024 above 5500",
  quote: "I doubt the S&P finishes the year above 5500.",
  claimType: "end_value_at_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "spx_close_end_2024",
  metricLabel: "S&P 500 close",
  threshold: 5500,
  unit: "index",
  status: "resolved",
  outcome: "yes",
  actualValue: "5689",
  evidenceUrl: "https://example.com/evidence/spx-2024",
  resolvedAt: "2024-12-31T21:00:00.000Z",
});
addClaim({
  expertSlug: "nouriel-roubini",
  title: "Conditional recession warning",
  platform: "TV interview",
  url: "https://example.com/roubini-conditional",
  publishedAt: "2025-01-05T15:00:00.000Z",
  eventKey: "conditional-recession",
  eventLabel: "Conditional recession claim",
  quote: "If the Fed cuts in September, we will see recession by Q2 2025.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "equals",
  metricKey: "conditional_recession",
  metricLabel: "Conditional recession call",
  unit: "binary",
  status: "rejected_unscoreable",
  rejectionReason: "Conditional claims are retained for audit but excluded from Phase 1 scoring.",
  llmSuggestedClaimType: "threshold_cross_by_date",
  llmSuggestedTier: "medium",
  llmConfidence: 0.78,
});

addClaim({
  expertSlug: "cathie-wood",
  title: "Risk assets rip on easing",
  platform: "Investor webcast",
  url: "https://example.com/cathie-spx",
  publishedAt: "2024-02-04T10:30:00.000Z",
  eventKey: "spx-above-5500-end-2024",
  eventLabel: "S&P 500 ends 2024 above 5500",
  quote: "We think the S&P can absolutely finish above 5500 this year.",
  claimType: "end_value_at_date",
  predictedOutcome: "yes",
  confidenceTier: "high",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "spx_close_end_2024",
  metricLabel: "S&P 500 close",
  threshold: 5500,
  unit: "index",
  status: "resolved",
  outcome: "yes",
  actualValue: "5689",
  evidenceUrl: "https://example.com/evidence/spx-2024",
  resolvedAt: "2024-12-31T21:00:00.000Z",
});
addClaim({
  expertSlug: "cathie-wood",
  title: "Fed cuts stack up",
  platform: "ARK note",
  url: "https://example.com/cathie-cuts",
  publishedAt: "2024-03-12T11:00:00.000Z",
  eventKey: "fed-three-cuts-2024",
  eventLabel: "Fed delivers at least three cuts in 2024",
  quote: "Our base case is that the Fed makes three cuts this year.",
  claimType: "count_by_deadline",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than_or_equal",
  metricKey: "fed_cuts_count_2024",
  metricLabel: "Fed cuts in 2024",
  threshold: 3,
  unit: "cuts",
  status: "resolved",
  outcome: "yes",
  actualValue: "3",
  evidenceUrl: "https://example.com/evidence/fed-cuts-count",
  resolvedAt: "2024-12-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "cathie-wood",
  title: "First cut comes before Q4",
  platform: "Podcast",
  url: "https://example.com/cathie-first-cut",
  publishedAt: "2024-04-01T14:00:00.000Z",
  eventKey: "fed-first-cut-by-q3-2024",
  eventLabel: "Fed delivers its first cut by the end of Q3 2024",
  quote: "There's a risk the first cut lands well before Q4.",
  claimType: "first_action_by_date",
  predictedOutcome: "yes",
  confidenceTier: "low",
  deadline: "2024-09-30T23:59:59.000Z",
  operator: "first_action_on_or_before",
  metricKey: "fed_funds_first_cut",
  metricLabel: "First Fed cut date",
  unit: "date",
  status: "resolved",
  outcome: "yes",
  actualValue: "2024-09-18",
  evidenceUrl: "https://example.com/evidence/fed-first-cut",
  resolvedAt: "2024-09-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "cathie-wood",
  title: "No recession call",
  platform: "Conference panel",
  url: "https://example.com/cathie-no-recession",
  publishedAt: "2024-05-15T16:00:00.000Z",
  eventKey: "us-recession-by-q2-2025",
  eventLabel: "US enters recession by Q2 2025",
  quote: "We do not see a recession by next summer.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "high",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "equals",
  metricKey: "nber_recession_start",
  metricLabel: "NBER recession start",
  threshold: 1,
  unit: "binary",
  status: "resolved",
  outcome: "no",
  actualValue: "0",
  evidenceUrl: "https://example.com/evidence/nber-q2-2025",
  resolvedAt: "2025-07-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "cathie-wood",
  title: "Labor holds together",
  platform: "Webinar",
  url: "https://example.com/cathie-unemployment",
  publishedAt: "2024-07-09T16:00:00.000Z",
  eventKey: "unemployment-above-4-5-end-2024",
  eventLabel: "US unemployment ends 2024 above 4.5%",
  quote: "We don't think unemployment closes the year above 4.5%.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "us_unemployment_rate_end_2024",
  metricLabel: "US unemployment rate",
  threshold: 4.5,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "4.1",
  evidenceUrl: "https://example.com/evidence/unemployment-2024",
  resolvedAt: "2025-01-10T13:00:00.000Z",
});
addClaim({
  expertSlug: "cathie-wood",
  title: "Inflation cools under 3%",
  platform: "ARK note",
  url: "https://example.com/cathie-cpi",
  publishedAt: "2024-08-14T11:00:00.000Z",
  eventKey: "cpi-below-3-end-2024",
  eventLabel: "US CPI ends 2024 below 3.0%",
  quote: "We expect CPI under 3% by the end of the year.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us_cpi_yoy_end_2024",
  metricLabel: "US CPI YoY",
  threshold: 3,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "3.2",
  evidenceUrl: "https://example.com/evidence/cpi-2024",
  resolvedAt: "2025-01-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "cathie-wood",
  title: "Oil never breaks triple digits",
  platform: "TV interview",
  url: "https://example.com/cathie-oil",
  publishedAt: "2025-01-09T15:00:00.000Z",
  eventKey: "brent-above-100-by-mid-2025",
  eventLabel: "Brent crude trades above $100 by June 2025",
  quote: "I don't think oil gets back above $100 by mid-year.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "brent_high_h1_2025",
  metricLabel: "Brent crude high",
  threshold: 100,
  unit: "USD",
  status: "resolved",
  outcome: "no",
  actualValue: "91",
  evidenceUrl: "https://example.com/evidence/brent-h1-2025",
  resolvedAt: "2025-06-30T20:00:00.000Z",
});

addClaim({
  expertSlug: "mohamed-el-erian",
  title: "Three cuts are enough",
  platform: "FT op-ed",
  url: "https://example.com/elerian-cuts",
  publishedAt: "2024-03-28T08:00:00.000Z",
  eventKey: "fed-three-cuts-2024",
  eventLabel: "Fed delivers at least three cuts in 2024",
  quote: "The base path now likely includes three cuts by year-end.",
  claimType: "count_by_deadline",
  predictedOutcome: "yes",
  confidenceTier: "low",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than_or_equal",
  metricKey: "fed_cuts_count_2024",
  metricLabel: "Fed cuts in 2024",
  threshold: 3,
  unit: "cuts",
  status: "resolved",
  outcome: "yes",
  actualValue: "3",
  evidenceUrl: "https://example.com/evidence/fed-cuts-count",
  resolvedAt: "2024-12-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "mohamed-el-erian",
  title: "First cut by Q3",
  platform: "Bloomberg TV",
  url: "https://example.com/elerian-first-cut",
  publishedAt: "2024-04-19T10:00:00.000Z",
  eventKey: "fed-first-cut-by-q3-2024",
  eventLabel: "Fed delivers its first cut by the end of Q3 2024",
  quote: "I think the first cut comes before the fourth quarter.",
  claimType: "first_action_by_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2024-09-30T23:59:59.000Z",
  operator: "first_action_on_or_before",
  metricKey: "fed_funds_first_cut",
  metricLabel: "First Fed cut date",
  unit: "date",
  status: "resolved",
  outcome: "yes",
  actualValue: "2024-09-18",
  evidenceUrl: "https://example.com/evidence/fed-first-cut",
  resolvedAt: "2024-09-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "mohamed-el-erian",
  title: "No recession in sight",
  platform: "Conference panel",
  url: "https://example.com/elerian-no-recession",
  publishedAt: "2024-05-08T16:00:00.000Z",
  eventKey: "us-recession-by-q2-2025",
  eventLabel: "US enters recession by Q2 2025",
  quote: "I don't see recession by the middle of next year.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "equals",
  metricKey: "nber_recession_start",
  metricLabel: "NBER recession start",
  threshold: 1,
  unit: "binary",
  status: "resolved",
  outcome: "no",
  actualValue: "0",
  evidenceUrl: "https://example.com/evidence/nber-q2-2025",
  resolvedAt: "2025-07-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "mohamed-el-erian",
  title: "Labor avoids 4.5%",
  platform: "Newsletter",
  url: "https://example.com/elerian-unemployment",
  publishedAt: "2024-06-17T09:00:00.000Z",
  eventKey: "unemployment-above-4-5-end-2024",
  eventLabel: "US unemployment ends 2024 above 4.5%",
  quote: "The more likely outcome is that unemployment stays below 4.5%.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "us_unemployment_rate_end_2024",
  metricLabel: "US unemployment rate",
  threshold: 4.5,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "4.1",
  evidenceUrl: "https://example.com/evidence/unemployment-2024",
  resolvedAt: "2025-01-10T13:00:00.000Z",
});
addClaim({
  expertSlug: "mohamed-el-erian",
  title: "Inflation remains sticky",
  platform: "Podcast",
  url: "https://example.com/elerian-cpi",
  publishedAt: "2024-08-11T10:00:00.000Z",
  eventKey: "cpi-below-3-end-2024",
  eventLabel: "US CPI ends 2024 below 3.0%",
  quote: "Base case: CPI doesn't finish the year under 3%.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us_cpi_yoy_end_2024",
  metricLabel: "US CPI YoY",
  threshold: 3,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "3.2",
  evidenceUrl: "https://example.com/evidence/cpi-2024",
  resolvedAt: "2025-01-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "mohamed-el-erian",
  title: "Yields can break lower",
  platform: "TV interview",
  url: "https://example.com/elerian-yields",
  publishedAt: "2024-09-02T12:00:00.000Z",
  eventKey: "ten-year-below-3-5-end-2024",
  eventLabel: "US 10Y Treasury ends 2024 below 3.5%",
  quote: "There is a risk the 10-year ends the year below 3.5%.",
  claimType: "end_value_at_date",
  predictedOutcome: "yes",
  confidenceTier: "low",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us10y_close_end_2024",
  metricLabel: "US 10Y Treasury",
  threshold: 3.5,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "4.0",
  evidenceUrl: "https://example.com/evidence/us10y-2024",
  resolvedAt: "2024-12-31T21:00:00.000Z",
});

addClaim({
  expertSlug: "lyn-alden",
  title: "Cuts are coming but not a crash",
  platform: "Research note",
  url: "https://example.com/lyn-cuts",
  publishedAt: "2024-02-29T11:00:00.000Z",
  eventKey: "fed-three-cuts-2024",
  eventLabel: "Fed delivers at least three cuts in 2024",
  quote: "My read is three cuts is a reasonable target for 2024.",
  claimType: "count_by_deadline",
  predictedOutcome: "yes",
  confidenceTier: "low",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than_or_equal",
  metricKey: "fed_cuts_count_2024",
  metricLabel: "Fed cuts in 2024",
  threshold: 3,
  unit: "cuts",
  status: "resolved",
  outcome: "yes",
  actualValue: "3",
  evidenceUrl: "https://example.com/evidence/fed-cuts-count",
  resolvedAt: "2024-12-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "lyn-alden",
  title: "No recession by Q2 2025",
  platform: "YouTube transcript",
  url: "https://example.com/lyn-no-recession",
  publishedAt: "2024-05-20T14:00:00.000Z",
  eventKey: "us-recession-by-q2-2025",
  eventLabel: "US enters recession by Q2 2025",
  quote: "I don't think we get recession by Q2 of next year.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "low",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "equals",
  metricKey: "nber_recession_start",
  metricLabel: "NBER recession start",
  threshold: 1,
  unit: "binary",
  status: "resolved",
  outcome: "no",
  actualValue: "0",
  evidenceUrl: "https://example.com/evidence/nber-q2-2025",
  resolvedAt: "2025-07-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "lyn-alden",
  title: "Inflation under 3 is a reach",
  platform: "Research note",
  url: "https://example.com/lyn-cpi",
  publishedAt: "2024-07-25T10:00:00.000Z",
  eventKey: "cpi-below-3-end-2024",
  eventLabel: "US CPI ends 2024 below 3.0%",
  quote: "I'm fairly confident CPI does not end 2024 below 3%.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "high",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us_cpi_yoy_end_2024",
  metricLabel: "US CPI YoY",
  threshold: 3,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "3.2",
  evidenceUrl: "https://example.com/evidence/cpi-2024",
  resolvedAt: "2025-01-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "lyn-alden",
  title: "Equities still grind higher",
  platform: "Podcast",
  url: "https://example.com/lyn-spx",
  publishedAt: "2024-08-08T15:00:00.000Z",
  eventKey: "spx-above-5500-end-2024",
  eventLabel: "S&P 500 ends 2024 above 5500",
  quote: "My base case is still above 5500 by year end.",
  claimType: "end_value_at_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "spx_close_end_2024",
  metricLabel: "S&P 500 close",
  threshold: 5500,
  unit: "index",
  status: "resolved",
  outcome: "yes",
  actualValue: "5689",
  evidenceUrl: "https://example.com/evidence/spx-2024",
  resolvedAt: "2024-12-31T21:00:00.000Z",
});
addClaim({
  expertSlug: "lyn-alden",
  title: "Yields stay elevated",
  platform: "Newsletter",
  url: "https://example.com/lyn-yields",
  publishedAt: "2024-09-18T12:00:00.000Z",
  eventKey: "ten-year-below-3-5-end-2024",
  eventLabel: "US 10Y Treasury ends 2024 below 3.5%",
  quote: "No, I don't think the 10-year ends 2024 below 3.5%.",
  claimType: "end_value_at_date",
  predictedOutcome: "no",
  confidenceTier: "high",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us10y_close_end_2024",
  metricLabel: "US 10Y Treasury",
  threshold: 3.5,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "4.0",
  evidenceUrl: "https://example.com/evidence/us10y-2024",
  resolvedAt: "2024-12-31T21:00:00.000Z",
});
addClaim({
  expertSlug: "lyn-alden",
  title: "Oil stays below $100",
  platform: "YouTube transcript",
  url: "https://example.com/lyn-oil",
  publishedAt: "2025-01-04T12:00:00.000Z",
  eventKey: "brent-above-100-by-mid-2025",
  eventLabel: "Brent crude trades above $100 by June 2025",
  quote: "My expectation is that Brent does not trade above $100 in the first half.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "brent_high_h1_2025",
  metricLabel: "Brent crude high",
  threshold: 100,
  unit: "USD",
  status: "resolved",
  outcome: "no",
  actualValue: "91",
  evidenceUrl: "https://example.com/evidence/brent-h1-2025",
  resolvedAt: "2025-06-30T20:00:00.000Z",
});

addClaim({
  expertSlug: "ed-yardeni",
  title: "Soft landing plus cuts",
  platform: "Morning note",
  url: "https://example.com/yardeni-cuts",
  publishedAt: "2024-03-05T09:00:00.000Z",
  eventKey: "fed-three-cuts-2024",
  eventLabel: "Fed delivers at least three cuts in 2024",
  quote: "Three cuts feels reasonable for a soft landing year.",
  claimType: "count_by_deadline",
  predictedOutcome: "yes",
  confidenceTier: "low",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than_or_equal",
  metricKey: "fed_cuts_count_2024",
  metricLabel: "Fed cuts in 2024",
  threshold: 3,
  unit: "cuts",
  status: "resolved",
  outcome: "yes",
  actualValue: "3",
  evidenceUrl: "https://example.com/evidence/fed-cuts-count",
  resolvedAt: "2024-12-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "ed-yardeni",
  title: "No recession call",
  platform: "Research webcast",
  url: "https://example.com/yardeni-no-recession",
  publishedAt: "2024-05-13T13:00:00.000Z",
  eventKey: "us-recession-by-q2-2025",
  eventLabel: "US enters recession by Q2 2025",
  quote: "We remain in the no-recession camp into mid-2025.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "equals",
  metricKey: "nber_recession_start",
  metricLabel: "NBER recession start",
  threshold: 1,
  unit: "binary",
  status: "resolved",
  outcome: "no",
  actualValue: "0",
  evidenceUrl: "https://example.com/evidence/nber-q2-2025",
  resolvedAt: "2025-07-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "ed-yardeni",
  title: "Jobs avoid a hard crack",
  platform: "Market note",
  url: "https://example.com/yardeni-jobs",
  publishedAt: "2024-06-30T10:00:00.000Z",
  eventKey: "unemployment-above-4-5-end-2024",
  eventLabel: "US unemployment ends 2024 above 4.5%",
  quote: "The labor market likely stays below 4.5% unemployment.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "us_unemployment_rate_end_2024",
  metricLabel: "US unemployment rate",
  threshold: 4.5,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "4.1",
  evidenceUrl: "https://example.com/evidence/unemployment-2024",
  resolvedAt: "2025-01-10T13:00:00.000Z",
});
addClaim({
  expertSlug: "ed-yardeni",
  title: "Stocks stay bid",
  platform: "TV interview",
  url: "https://example.com/yardeni-spx",
  publishedAt: "2024-07-17T10:00:00.000Z",
  eventKey: "spx-above-5500-end-2024",
  eventLabel: "S&P 500 ends 2024 above 5500",
  quote: "I expect the S&P to end the year above 5500.",
  claimType: "end_value_at_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "spx_close_end_2024",
  metricLabel: "S&P 500 close",
  threshold: 5500,
  unit: "index",
  status: "resolved",
  outcome: "yes",
  actualValue: "5689",
  evidenceUrl: "https://example.com/evidence/spx-2024",
  resolvedAt: "2024-12-31T21:00:00.000Z",
});
addClaim({
  expertSlug: "ed-yardeni",
  title: "Inflation under 3%",
  platform: "Morning note",
  url: "https://example.com/yardeni-cpi",
  publishedAt: "2024-08-06T09:00:00.000Z",
  eventKey: "cpi-below-3-end-2024",
  eventLabel: "US CPI ends 2024 below 3.0%",
  quote: "There's a reasonable chance CPI closes under 3%.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "yes",
  confidenceTier: "low",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us_cpi_yoy_end_2024",
  metricLabel: "US CPI YoY",
  threshold: 3,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "3.2",
  evidenceUrl: "https://example.com/evidence/cpi-2024",
  resolvedAt: "2025-01-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "ed-yardeni",
  title: "Rates break lower",
  platform: "Webcast",
  url: "https://example.com/yardeni-yields",
  publishedAt: "2024-09-20T15:00:00.000Z",
  eventKey: "ten-year-below-3-5-end-2024",
  eventLabel: "US 10Y Treasury ends 2024 below 3.5%",
  quote: "I think the 10-year can still end 2024 below 3.5%.",
  claimType: "end_value_at_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us10y_close_end_2024",
  metricLabel: "US 10Y Treasury",
  threshold: 3.5,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "4.0",
  evidenceUrl: "https://example.com/evidence/us10y-2024",
  resolvedAt: "2024-12-31T21:00:00.000Z",
});
addClaim({
  expertSlug: "ed-yardeni",
  title: "Oil stays below $100",
  platform: "TV interview",
  url: "https://example.com/yardeni-oil",
  publishedAt: "2025-01-02T15:00:00.000Z",
  eventKey: "brent-above-100-by-mid-2025",
  eventLabel: "Brent crude trades above $100 by June 2025",
  quote: "My call is still that Brent doesn't see $100 by mid-year.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "no",
  confidenceTier: "medium",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "brent_high_h1_2025",
  metricLabel: "Brent crude high",
  threshold: 100,
  unit: "USD",
  status: "resolved",
  outcome: "no",
  actualValue: "91",
  evidenceUrl: "https://example.com/evidence/brent-h1-2025",
  resolvedAt: "2025-06-30T20:00:00.000Z",
});

addClaim({
  expertSlug: "jim-cramer",
  title: "Stocks stay hot but labor cracks",
  platform: "TV hit",
  url: "https://example.com/cramer-unemployment",
  publishedAt: "2024-03-14T16:00:00.000Z",
  eventKey: "unemployment-above-4-5-end-2024",
  eventLabel: "US unemployment ends 2024 above 4.5%",
  quote: "I think unemployment goes above 4.5% by year end.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "yes",
  confidenceTier: "high",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "us_unemployment_rate_end_2024",
  metricLabel: "US unemployment rate",
  threshold: 4.5,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "4.1",
  evidenceUrl: "https://example.com/evidence/unemployment-2024",
  resolvedAt: "2025-01-10T13:00:00.000Z",
});
addClaim({
  expertSlug: "jim-cramer",
  title: "Fed never gets to three cuts",
  platform: "Mad Money",
  url: "https://example.com/cramer-cuts",
  publishedAt: "2024-03-30T20:00:00.000Z",
  eventKey: "fed-three-cuts-2024",
  eventLabel: "Fed delivers at least three cuts in 2024",
  quote: "No way the Fed gets to three cuts this year.",
  claimType: "count_by_deadline",
  predictedOutcome: "no",
  confidenceTier: "high",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than_or_equal",
  metricKey: "fed_cuts_count_2024",
  metricLabel: "Fed cuts in 2024",
  threshold: 3,
  unit: "cuts",
  status: "resolved",
  outcome: "yes",
  actualValue: "3",
  evidenceUrl: "https://example.com/evidence/fed-cuts-count",
  resolvedAt: "2024-12-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "jim-cramer",
  title: "First cut slips into Q4",
  platform: "TV hit",
  url: "https://example.com/cramer-first-cut",
  publishedAt: "2024-04-22T18:00:00.000Z",
  eventKey: "fed-first-cut-by-q3-2024",
  eventLabel: "Fed delivers its first cut by the end of Q3 2024",
  quote: "The first cut is not coming before Q4, period.",
  claimType: "first_action_by_date",
  predictedOutcome: "no",
  confidenceTier: "high",
  deadline: "2024-09-30T23:59:59.000Z",
  operator: "first_action_on_or_before",
  metricKey: "fed_funds_first_cut",
  metricLabel: "First Fed cut date",
  unit: "date",
  status: "resolved",
  outcome: "yes",
  actualValue: "2024-09-18",
  evidenceUrl: "https://example.com/evidence/fed-first-cut",
  resolvedAt: "2024-09-18T20:00:00.000Z",
});
addClaim({
  expertSlug: "jim-cramer",
  title: "Inflation glides under 3%",
  platform: "TV hit",
  url: "https://example.com/cramer-cpi",
  publishedAt: "2024-07-30T18:00:00.000Z",
  eventKey: "cpi-below-3-end-2024",
  eventLabel: "US CPI ends 2024 below 3.0%",
  quote: "Inflation is going below 3% by the end of the year.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "yes",
  confidenceTier: "high",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us_cpi_yoy_end_2024",
  metricLabel: "US CPI YoY",
  threshold: 3,
  unit: "%",
  status: "resolved",
  outcome: "no",
  actualValue: "3.2",
  evidenceUrl: "https://example.com/evidence/cpi-2024",
  resolvedAt: "2025-01-15T13:00:00.000Z",
});
addClaim({
  expertSlug: "jim-cramer",
  title: "S&P still closes strong",
  platform: "Mad Money",
  url: "https://example.com/cramer-spx",
  publishedAt: "2024-08-18T18:00:00.000Z",
  eventKey: "spx-above-5500-end-2024",
  eventLabel: "S&P 500 ends 2024 above 5500",
  quote: "This market has enough juice to close above 5500.",
  claimType: "end_value_at_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2024-12-31T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "spx_close_end_2024",
  metricLabel: "S&P 500 close",
  threshold: 5500,
  unit: "index",
  status: "resolved",
  outcome: "yes",
  actualValue: "5689",
  evidenceUrl: "https://example.com/evidence/spx-2024",
  resolvedAt: "2024-12-31T21:00:00.000Z",
});
addClaim({
  expertSlug: "jim-cramer",
  title: "Oil spikes back above $100",
  platform: "TV hit",
  url: "https://example.com/cramer-oil",
  publishedAt: "2025-01-12T17:00:00.000Z",
  eventKey: "brent-above-100-by-mid-2025",
  eventLabel: "Brent crude trades above $100 by June 2025",
  quote: "Oil can easily trade back above $100 by summer.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "yes",
  confidenceTier: "high",
  deadline: "2025-06-30T23:59:59.000Z",
  operator: "greater_than",
  metricKey: "brent_high_h1_2025",
  metricLabel: "Brent crude high",
  threshold: 100,
  unit: "USD",
  status: "resolved",
  outcome: "no",
  actualValue: "91",
  evidenceUrl: "https://example.com/evidence/brent-h1-2025",
  resolvedAt: "2025-06-30T20:00:00.000Z",
});
addClaim({
  expertSlug: "jim-cramer",
  title: "Broad timing claim",
  platform: "TV hit",
  url: "https://example.com/cramer-broad",
  publishedAt: "2025-02-18T17:00:00.000Z",
  eventKey: "rates-down-significantly",
  eventLabel: "Rates come down significantly in the next few years",
  quote: "Rates will come down significantly in the next few years.",
  claimType: "end_value_at_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2027-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "rates_broad",
  metricLabel: "Broad rates call",
  unit: "binary",
  status: "rejected_unscoreable",
  rejectionReason: "Missing deadline precision and threshold specificity.",
  llmSuggestedClaimType: "end_value_at_date",
  llmSuggestedTier: "medium",
  llmConfidence: 0.75,
});

addClaim({
  expertSlug: "cathie-wood",
  title: "Open 2026 inflation call",
  platform: "Podcast",
  url: "https://example.com/cathie-open-2026",
  publishedAt: "2026-02-01T12:00:00.000Z",
  eventKey: "cpi-below-2-5-end-2026",
  eventLabel: "US CPI ends 2026 below 2.5%",
  quote: "We think CPI gets under 2.5% by the end of 2026.",
  claimType: "threshold_cross_by_date",
  predictedOutcome: "yes",
  confidenceTier: "medium",
  deadline: "2026-12-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us_cpi_yoy_end_2026",
  metricLabel: "US CPI YoY",
  threshold: 2.5,
  unit: "%",
  status: "published_open",
});
addClaim({
  expertSlug: "lyn-alden",
  title: "Awaiting payroll data",
  platform: "Research note",
  url: "https://example.com/lyn-awaiting-data",
  publishedAt: "2026-01-12T12:00:00.000Z",
  eventKey: "payroll-below-100k-march-2026",
  eventLabel: "March 2026 payroll growth prints below 100k",
  quote: "I expect payroll growth below 100k by March.",
  claimType: "end_value_at_date",
  predictedOutcome: "yes",
  confidenceTier: "low",
  deadline: "2026-03-31T23:59:59.000Z",
  operator: "less_than",
  metricKey: "us_payroll_march_2026",
  metricLabel: "US payroll growth",
  threshold: 100,
  unit: "k",
  status: "published_awaiting_data",
});

const changelogEntries: ChangelogEntry[] = [
  {
    id: "changelog-v1-0",
    version: "v1.0",
    publishedAt: "2026-03-03T09:00:00.000Z",
    title: "Launch scoring frozen for the quarter",
    summary: "AYRE froze prior quality, shrinkage K, and the confidence tier map for the entire v1.0 window.",
    changes: [
      "Set shrinkage K to 12 after comparing rank stability across 8, 12, 16, and 20.",
      "Locked the tier map at 0.60 / 0.70 / 0.80 for low, medium, and high conviction.",
      "Added scoreVersion to public cards so archived shares stay interpretable after future recalibration.",
    ],
  },
];

const correctionRequests: CorrectionRequest[] = [
  {
    id: "correction-1",
    expertSlug: "nouriel-roubini",
    claimId: "claim-7",
    status: "temporarily_unpublished",
    submittedAt: "2026-03-09T10:00:00.000Z",
    summary: "Conditional claim was challenged as non-scoreable and was pulled pending review.",
  },
  {
    id: "correction-2",
    expertSlug: "jim-cramer",
    claimId: "claim-36",
    status: "pending_review",
    submittedAt: "2026-03-15T15:00:00.000Z",
    summary: "Submitter argues the quote is too broad to score and should remain rejected.",
  },
  {
    id: "correction-3",
    expertSlug: "cathie-wood",
    status: "corrected",
    submittedAt: "2026-03-18T18:00:00.000Z",
    summary: "Source URL updated to a primary webcast archive after a broken link report.",
  },
];

const launchGates: LaunchGate[] = [
  {
    label: "20 experts seeded",
    detail: "Mock board is below target, so the admin gate remains open.",
    status: "in_progress",
  },
  {
    label: "400+ resolved claims",
    detail: "Sample data demonstrates the schema, not the final launch density.",
    status: "in_progress",
  },
  {
    label: "K and tier map calibrated",
    detail: "v1.0 is frozen with K=12 and a 0.60 / 0.70 / 0.80 tier map.",
    status: "done",
  },
  {
    label: "Legal copy reviewed",
    detail: "Methodology, changelog, and corrections copy are wired into the public footer.",
    status: "done",
  },
];

export const mockSiteDataset: SiteDataset = {
  launchDate: activeScoreVersion.activatedAt,
  activeScoreVersion,
  scoringVersions,
  experts,
  sourceDocuments,
  claims,
  resolutions,
  changelogEntries,
  correctionRequests,
  launchGates,
};
